[package]
name = "controller"
version = "0.1.0"
edition.workspace = true

[lib]
name = "controller"
path = "src/controller.rs"

[dependencies]
tracing.workspace = true
tokio.workspace = true
anyhow.workspace = true
sequencer.path = "../sequencer"
gphoto.path = "../drivers/gphoto"

[lints]
workspace = true
