[package]
name = "apogee"
version = "0.1.0"
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
wgpu.workspace = true
planetarium = { path = "../planetarium" }
workspace = { path = "../workspace" }
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
