[package]
name = "workspace"
version = "0.1.0"
edition.workspace = true

[lib]
name = "workspace"
path = "src/workspace.rs"

[dependencies]
gpui.workspace = true
ui.workspace = true
theme.workspace = true
tracing.workspace = true
status_bar.path = "../status_bar"

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
